# Yousef ELsayed G01259710
# Lab 5: section 215
# Lab5: makefile



CC = gcc
CFLAGS = -g -Wall -std=c89 -pedantic-errors
TARGET = P1_yelsayed_215
LIB = -lm



$(TARGET):$(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS)



clear:
	rm $(TARGET)
