# Yousef Elsayed G01259710
# Lab 9: lab section215
# Lab 9: makefile


TARGET = lab9_yelsayed_215
CC = gcc
CFLAGS = -std=c89 -pedantic-errors
LIB = -lm


$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIB)

clear:
	rm $(TARGET)
