# Yousef Elsayed G01259710
# Project 2: sections 215
# Project 2: Makefile



CC = gcc
CFLAGS = -g -Wall -std=c89 -pedantic-errors
TARGET = p2_yelsayed_215
LIB = -lm



$(TARGET):$(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS)




clear:
	rm $(TARGET)
